### ISSUE TITLE
What is the difference between nrnrk/gocognito and uudashr/gocognit?

### ISSUE THREAD

**Issue by sonatard** [nrnrk/gocognito#1]
I would like to use Cognitive Complexity's Linter and would be glad to know what the difference is!

https://github.com/uudashr/gocognit

**Comment by nrnrk** [comment]
Almost same for now.

This repository is created based on [gocognit](https://github.com/uudashr/gocognit). But there are 2 different pioins, as far as I know.


The difference is the followings:

1. `gocognit` has more command line options than `gocognito`
2. Different calculations of a sequence of logical binary operators


> 1. `gocognit` has more command line options than `gocognito`

I would like to add more options in the future. I hope that `gocognito` will catch up with `gocognit`. 

> 2. Different calculations for a sequence of logical binary operators

`gocognit` will output 3 for cognitive complexity for this [testcase](https://github.com/nrnrk/gocognito/blob/main/testdata/src/a/a.go#L78)

But `gocognito` will output 4 for cognitive complexity for it.

[The white paper of cognitive complexity](https://www.sonarsource.com/docs/CognitiveComplexity.pdf) does not define this case. The paper just defines "increment when encounters 'sequences of binary logical operators'" and I believe that `(a && b || c) || d` consists of 3 parts of sequences, not 2.

**Comment by sonatard** [comment]
I understand very well Thanks!
